<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>SmolBit</string>
	<key>scopeName</key>
	<string>source.smolbit</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment.smolbit</string>
			<key>match</key>
			<string>;([\s|\S]*);</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.smolbit</string>
			<key>match</key>
			<string>"([\s|\S]*)"</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(DEF|CLL|UDF)[\(\s]?([0-9a-f])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.smolbit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.smolbit</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.smolbit</string>
			<key>match</key>
			<string>(DEF|IF|FOR|VFR|UDF|CLL|WHL|REP)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.smolbit</string>
			<key>match</key>
			<string>(ADD|SUB|MUL|DIV|SET|LDI|LD2|LD3|LD4|POW|ROT)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.comparison.smolbit</string>
			<key>match</key>
			<string>(=|&gt;|&lt;|!)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.smolbit</string>
			<key>match</key>
			<string>([0-9a-f]{2})</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.variable.smolbit</string>
			<key>match</key>
			<string>([0-9a-e]{1})</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.variable.global.smolbit</string>
			<key>match</key>
			<string>([f]{1})</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.smolbit</string>
			<key>match</key>
			<string>(PG1|PG2|PG3|PG4|PG5|PG6|PG7|PG8)</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.smolbit</string>
			<key>match</key>
			<string>(PUS|POP|DPI|DPD|DPH|DPM|DPU|EXO|EXE|INH|IND|INC|DEC|CLZ|CLI|NOP)</string>
		</dict>
	</array>
</dict>
</plist>